baseurl: /cpp-programs

collections:
  getting_started:
    output: true
  standard_library:
    output: true

defaults:
  - scope:
      path: ""
      type: "getting_started"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "standard_library"
    values:
      layout: "page"

exclude: [Gemfile]